version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/KinkoTestV2
    command: ["--source", "traveltodo", "--destination", "Hammamet", "--checkIn", "2024-08-13", "--nbNights", "1"]
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=kinkotest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hsan
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: kinkotest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hsan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
